export const UPDATE_SESSIONS = 'UPDATE_SESSIONS';
export const UPDATE_SELECTED_SESSIONS = 'UPDATE_SELECTED_SESSIONS';
export const UPDATE_SELECTED_CHAT = 'UPDATE_SELECTED_CHAT';
export const LOGIN = 'LOGIN';
export const LOADER = 'LOADER';
export const APP_LOGO = 'APP_LOGO';
